AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Lambda para cadastro de usu\xE1rios com Cognito"
Globals:
  Function:
    Runtime: go1.x
    Timeout: 10
    MemorySize: 128
Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: UserPoolCadastro
      AutoVerifiedAttributes:
      - email
      UsernameAttributes:
      - email
  UserSignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CadastroUsuarioFunction
      Handler: main
      CodeUri: UserSignupFunction
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - cognito-idp:AdminCreateUser
          Resource:
            Fn::GetAtt:
            - CognitoUserPool
            - Arn
      Environment:
        Variables:
          USER_POOL_ID:
            Ref: CognitoUserPool
    Metadata:
      SamResourceId: UserSignupFunction
